apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogify-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blogify
  template:
    metadata:
      labels:
        app: blogify
    spec:
      containers:
        - name: blogify
          image: sanjaysam001/blogify:latest
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 30  # Time to wait before performing the first check
            periodSeconds: 10         # Time interval between each check
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 30   # Time to wait before performing the first check
            periodSeconds: 10         # Time interval between each check
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"