apiVersion: v1
kind: Service
metadata:
  name: blogify-ssvc
  
spec:
  selector:
    app: blogify
  ports:
    - protocol: TCP
      port: 8000           # Expose the service on standard HTTP port
      targetPort: 8000   # Redirect to the application's container port
  type: LoadBalancer
  